### ISSUE TITLE
Add architect in manu bar in chatbox

### ISSUE THREAD

**Issue by tuanlv14** [lee88688/aider-composer#12]
Pls add a feature to use architect mode with aider like as ask & code.

**Comment by lee88688** [comment]
do you usually use architect mode?

**Comment by tuanlv14** [comment]
yes. architect mode is good mode with reasoning model to complete code.

**Comment by bhupesh-sf** [comment]
Yes, even I was about to suggest the same.

**Comment by AlexJ-StL** [comment]
+1
I too use Aider almost exclusively in Architect or Code modes. I actually came to this repo from VSC to see if there was discussions of adding Arch mode and multi-model switching/toggling. It appears that they have both been requested a good amount.

**Comment by lee88688** [comment]
> +1 I too use Aider almost exclusively in Architect or Code modes. I actually came to this repo from VSC to see if there was discussions of adding Arch mode and multi-model switching/toggling. It appears that they have both been requested a good amount.

what arch and editor models does you usually use? I don't use Architect in Aider. so I don't have any requirements. is the Architect  mode really good?

**Comment by AlexJ-StL** [comment]
> > +1 I too use Aider almost exclusively in Architect or Code modes. I actually came to this repo from VSC to see if there was discussions of adding Arch mode and multi-model switching/toggling. It appears that they have both been requested a good amount.
> 
> what arch and editor models does you usually use? I don't use Architect in Aider. so I don't have any requirements. is the Architect mode really good?

I have been using either Claude 3.5 Sonnet or Gemini-1.5-Pro or Experimental for the architect model and SombaNova/Llama-3.1-405B, Mistral/Codestral, Groq/Llama-70B, Deepseek-2.5, or local models with LM Studio* for the editor model. I have been having good luck with Gemini-1.5-exp1121** architect & SombaNova/Llama-3.1-405B editor and Claude-3.5 architect & Deepseek-2.5. For whatever reason the "handshake" or "handoff" between the planning model and the coding model works well for me with those two combos. 

The brilliant part to me, and something we should all take advantage of while it is available, is that all of those are free with the exception of Claude Sonnet. In my initial testing the Claude Haiku model seems to be just as good now, so I was going to start running that one to see if it works as well.

Well, I hope that this helps. If I can help you with anything else let me know.

*Ollama is also excellent, but I am just used to and prefer the LM Studio GUI
**I think that is the correct date for the non-"learning" Gemini experimental model

**Comment by AlexJ-StL** [comment]
@lee88688 

I also just remembered the blog article that Paul or whoever wrote back in September about the quantifiable differences between simply running with 1 model for planning and execution, juxtaposed to separating the functions between two models or two "personas". Its fascinating and, at least for me, bears out in my use of LLMs for the past 2-3 years. Here is the link to the article. It is a short read and they did a great job of visually presenting the data. https://aider.chat/2024/09/26/architect.html

**Comment by lee88688** [comment]
as I see in the [aiser's code](https://github.com/Aider-AI/aider/blob/51c02da206c82373895a142be560de4acd96d8f2/aider/coders/base_coder.py#L1311), architect editor runs seperately. this do not return any llms chunks from function `send_message`, so the extension webview does not have any messages or event do not known about it.

so there may be some problems to implement in the extension.

**Comment by AlexJ-StL** [comment]
I don't know that I follow what you are saying, but that is on me because I haven't really taken the time to look through all the code for this extension or for Aider. With that said, I will have to investigate further into the extension's code to have anything intelligent to add. I do have a theory that I will look into tonight and report back if my theory works out.

> as I see in the [aiser's code](https://github.com/Aider-AI/aider/blob/51c02da206c82373895a142be560de4acd96d8f2/aider/coders/base_coder.py#L1311), architect editor runs seperately. this do not return any llms chunks from function `send_message`, so the extension webview does not have any messages or event do not known about it.
> 
> so there may be some problems to implement in the extension.
