### ISSUE TITLE
Accept / Reject don't work unless I click on the block code before

### ISSUE THREAD

**Issue by PhunkyBob** [lee88688/aider-composer#19]
When I want to make some actions like "accept / reject", it doesn't work if I don't click on the block code.

## Steps to reproduce
- Ask a modification in my code in `diff` mode.
- Wait for the assistant to suggest modifications ("accept / reject").
- Click on "Accept".

## Expected result
- Code is accepted.

## Actual result
- Nothing is done.
- I can rush click on "Accept" or "Reject", nothing works.

## Additional informations
When I click on the modified block code, then the "accept / reject" click works.

![2024-11-22_15-11-54](https://github.com/user-attachments/assets/213eb6ab-75b8-486f-815c-e84de373eee5)

ps: very nice project!

**Comment by lee88688** [comment]
you can try [latest version](https://github.com/lee88688/aider-composer/releases/tag/v1.3.2)

**Comment by PhunkyBob** [comment]
> you can try [latest version](https://github.com/lee88688/aider-composer/releases/tag/v1.3.2)

It solved it!
