### ISSUE TITLE
How to set up using LMStudio

### ISSUE THREAD

**Issue by deltaminimal** [lee88688/aider-composer#24]
I could not figure that one out, if it's at all possible.

**Comment by lee88688** [comment]
LMStudio has openai compatible api? Aider support this.

**Comment by toolazyhhh** [comment]
https://lmstudio.ai/docs/api/server
You can refer to this url for setting up local server

**Comment by tardyon** [comment]
As of a few weeks ago LMStudio causes Aider to go into a loop and crash out. I'll see if it works now.

**Comment by toolazyhhh** [comment]
Cool, I am quite curious whether that will work out

**Comment by deltaminimal** [comment]
Ok, I got it working like this:

![image](https://github.com/user-attachments/assets/a7550ddf-3fc6-41af-bb75-1f23977d53b9)

the api key is "lm-studio" (without quotations)

The model identifier is in the LM-Studio Developer tab

![image](https://github.com/user-attachments/assets/ba352356-718a-4da1-a5a6-e0622ff6b295)

And the other address appears in the console after starting the server (if you are using a different port then the address will change)

![image](https://github.com/user-attachments/assets/9d50b0bc-f93a-4856-acec-c1c179319057)

Let me know if I can help with something else, otherwise I guess the issue has been resolved, sorry for posting it but without the article shared by @toolazyhhh it would have taken a long time for me to figure it out on my own.
