### ISSUE TITLE
Issue: Difficulty Viewing Diff View on Light Background

### ISSUE THREAD

**Issue by toolazyhhh** [lee88688/aider-composer#25]
When using the "Aider Composer" diff view, I find it difficult to see the differences because the background color is dark (black) while the code itself is on a light background. This contrast makes it hard to focus on the diff view.

Is there any way to adjust the theme or background color of the diff view for better visibility?

Thank you in advance for your help!
![image](https://github.com/user-attachments/assets/518598d7-c446-4eb7-88bb-651ad8fe235c)

**Comment by lee88688** [comment]
this is a good issue, I find a time to add it.

**Comment by toolazyhhh** [comment]
Thanks! Will definitely try it out
