### ISSUE TITLE
 aider-chat: TypeError: InputOutput.__init__() got an unexpected keyword argument 'fancy_input'

### ISSUE THREAD

**Issue by turiddu25** [lee88688/aider-composer#28]
Got this error and it just doesnt even start.
![{CB23C3DB-AFFF-4BBA-AD36-0DB4E93668E4}](https://github.com/user-attachments/assets/c1e5d1da-ac3f-4a94-bf56-aef71cb8e67e)

**Comment by lee88688** [comment]
Duplicate to #6 
You need update aider's version.
