### ISSUE TITLE
Python path

### ISSUE THREAD

**Issue by jcald1** [lee88688/aider-composer#44]
I'm getting an error stating the the Pytho path does not include python executable.

I tried setting it to the following:
```
/home/jorge/.local/bin
/home/jorge/.local/bin/aider
/usr/bin
/usr/bin/python3

```

```
in settings.json:
{
    "aider-composer.pythonPath": "/home/jorge/.local/bin",
...
```

```
which aider
/home/jorge/.local/bin/aider
```

```
which python3
/usr/bin/python3
```

```
aider --version
aider 0.64.1
```

On my system, only `python3` works, not the `python` command.

**Comment by lee88688** [comment]
python3 may not be supported. can you use python venv?

**Comment by 2823076507** [comment]
You're having an issue where the Python path doesn't include the Python executable. Here are some possible solutions:
Review and modify settings.json
You've already attempted to set the Python path in settings.json without success. Double-check that the file paths are accurate. From the information you provided, /usr/bin/python3 is the actual path of the python3 executable. So, you can directly set "aider-composer.pythonPath" to this value:
{
    "aider-composer.pythonPath": "/usr/bin/python3"
}

**Comment by jcald1** [comment]
Closing the issue. I was having some other problems with my Python environment due to flatpak.
