### ISSUE TITLE
Sonnet 3.5 responses don't seem to update files

### ISSUE THREAD

**Issue by jfcostello** [lee88688/aider-composer#5]
Have an issue on both my Mac and Windows installation using the VS code extension from marketplace. If I use GPT-4o as the model, it seems to grab the diffs automatically without issue, it edits the files automatically and I can compare the diffs

When using claude-3-5-sonnet-20241022, this seems to rarely work. Sometimes, when it sends back alot of changes, maybe one of them will be implemented, but the rest won't and mostly none of them are. I'll see the reply from Claude, it appears to be formatted correctly (Has the same Send, Receive, ======= etc) but I'll get an error saying something like 'LLM message not in correct format'. This is true no matter which option I select for Diff, diff-fenced, udiff or whole

**Comment by lee88688** [comment]
what provider do you use? openrouter?

**Comment by jfcostello** [comment]
I was using Anthropic with my own key, just switched to Openrouter and realize I think I was wrong on gpt-4o

What seems to be happening me now is I no longer get an error about the LLM responding in the wrong format, but on both Openrouter using Sonnet and OpenAI directly for GPT-4o, it seems to only implement the last edit. So whether it's one file or multiple files, the only change that seems to apply is whichever one is at the end of the message for whatever reason

**Comment by jfcostello** [comment]
Curious, looking at the logs, and it thinks it has modified one file multiple times and another file once

2024-11-14 10:04:33.433 [debug] aider-chat: write D:\Git-Projects\resume-builder-chrome\config.js
2024-11-14 10:04:33.433 [debug] aider-chat: write D:\Git-Projects\resume-builder-chrome\config.js
2024-11-14 10:04:33.433 [debug] aider-chat: write D:\Git-Projects\resume-builder-chrome\config.js
2024-11-14 10:04:33.433 [debug] aider-chat: write D:\Git-Projects\resume-builder-chrome\options.js
2024-11-14 10:04:33.433 [debug] aider-chat: Applied edit to config.js
2024-11-14 10:04:33.434 [debug] aider-chat: Applied edit to options.js
2024-11-14 10:04:33.453 [info] command write file: D:\Git-Projects\resume-builder-chrome\options.js
2024-11-14 10:04:33.453 [info] command write file: D:\Git-Projects\resume-builder-chrome\config.js

but the only one of those edits is shown in VS code, so I can only accept one that I know of. Weirdly, this time, it was the last config.js edit, rather than the last edit in the message. So it was the third of four edits it made. So the issue might just be in popping the diff up in VS code for me to accept, or user error on my part?

**Comment by lee88688** [comment]
for every edit, extension will give a diff editor to user, maybe this is an issue. let me try it locally.

**Comment by lee88688** [comment]
you can try latest version of extension to see whether it have problems.

**Comment by jfcostello** [comment]
Aha, yes, updated and this is now working - thank you so much for such a fast fix!
