### ISSUE TITLE
App will not work

### ISSUE THREAD

**Issue by thebobbyboy420** [lee88688/aider-composer#50]
I can not get this to work no matter what i try

[homepc@homepc-ms7b17 Downloads]$ which aider
/home/homepc/.local/bin/aider
[homepc@homepc-ms7b17 Downloads]$ which python
/usr/bin/python
[homepc@homepc-ms7b17 Downloads]$ which python3
/usr/bin/python3
[homepc@homepc-ms7b17 Downloads]$

![image](https://github.com/user-attachments/assets/c6a4234c-f1cd-4f5a-ab63-7e512ecd00c2)

**Comment by thebobbyboy420** [comment]
no help ? :(

**Comment by lee88688** [comment]
I'm sorry for that. but I dont't use mac. and these I can't handle. I have update some of the logic to find the python command. you can update the version and have a try. If you have any question, it's better to give the output message in the vscode.

**Comment by lee88688** [comment]
you can refer to #2 , there are some people to use mac. and some of them get resolved.

**Comment by thebobbyboy420** [comment]
i also dont use a mac

this is linux kde

**Comment by lee88688** [comment]
is this ok when you update the version?

**Comment by thebobbyboy420** [comment]
1.7.0 gives no python error but the extension does not show anywhere even after restarting vscode

**Comment by lee88688** [comment]
Can you paste the errors? The output or the error message.

**Comment by thebobbyboy420** [comment]
> Can you paste the errors? The output or the error message.

but there was no errors so how can i give you an error log?

**Comment by lee88688** [comment]
the output of the vscode for Aider Composer? and have you installed [flask and aider-chat](https://github.com/lee88688/aider-composer?tab=readme-ov-file#requirements) for your python command.

**Comment by thebobbyboy420** [comment]
> the output of the vscode for Aider Composer? and have you installed [flask and aider-chat](https://github.com/lee88688/aider-composer?tab=readme-ov-file#requirements) for your python command.

i have aider installed and it works in my terminal 

![image](https://github.com/user-attachments/assets/b016f7eb-1fcc-45fb-b9d9-fa2632262a02)

**Comment by lee88688** [comment]
flask package is also intall? and when Aider Composer start, it will log the server startup command in the output. you can find and excute in the terminal to see if all config is right. the log is like below

> 2024-12-24 09:34:13.438 [info] aider-chat process args: C:\Users\xxx\scoop\apps\miniconda\current\envs\aider\python.exe -m flask -A c:\Users\si.li\.vscode\extensions\lee2py.aider-composer-1.7.0\server\main.py run --port 11650

**Comment by thebobbyboy420** [comment]
this app is such a broken mess that 90% of people cant even get to work such a shame really wanted to test this out.

**Comment by lee88688** [comment]
> this app is such a broken mess that 90% of people cant even get to work such a shame really wanted to test this out.

how do you get 90% of the people can't get to work? this plugin is provide the people that use aider before. if you think this plugin is useless, just uninstall it.
