### ISSUE TITLE
Fails to show

### ISSUE THREAD

**Issue by evolu8** [lee88688/aider-composer#52]
The icon is not visible and the chat pane does not appear dispite previously being available and working. 
Geting this occasionally in the Output:
"ModuleNotFoundError: No module named 'aider.models'"

**Comment by lee88688** [comment]
I think you should read [requirements](https://github.com/lee88688/aider-composer?tab=readme-ov-file#requirements). you does not install required python packages.

**Comment by evolu8** [comment]
Hi. Actually I did, but the issue was some kind of profile level config corruption in VS Code. By simply making a new profile and adding the Extension to it, everything works fine again. The original profile still fails to load Aider-Composer (yet otherwise seems fine). 

If I ever figure out the settings clash I'll post it.

**Comment by lee88688** [comment]
> @lee88688 Hi. Actually I did, but the issue was some kind of profile level config corruption in VS Code. By simply making a new profile and adding the Extension to it, everything works fine again. The original profile still fails to load Aider-Composer (yet otherwise seems fine). I've tried uninstalling and reinstalling the extention many times to the old profile and it fails every time. There seems to be an incoherence between python environments used and expected. Probably user error, but tricky to undo it seems.

the new profile with same python path cofig? that is very strange. the output will log the startup command and you can have a try in your terminal to see if it have problems.

**Comment by wht300** [comment]
You can try using pip install aider-chat instead of other methods.
I encountered the same error as you.
In my case, after following one of the recommended installation methods for aider-chat—using pipx (pipx install aider-chat)—and attempting to use it with aider-composer, I encountered the error: "ModuleNotFoundError: No module named 'aider.models'".
After uninstalling it and reinstalling it with pip install aider-chat, and then starting aider-composer again, it successfully launched aider-composer.

**Comment by 2e3s** [comment]
>  After uninstalling it and reinstalling it with pip install aider-chat, and then starting aider-composer again, it successfully launched aider-composer.

Just a note, there is no need to uninstall the pipx package, I think.

The requirement of venv is a major pitfall though. The why is understandable, but it takes noticeable effort and leaves unnecessary traces, namely the folder. Some Visual Studio extensions download the required environment on installation, this extension could do this too, I suppose. E.g. by creating a venv itself.
