### ISSUE TITLE
Incompatible with Homebrew Python

### ISSUE THREAD

**Issue by jialanxin** [lee88688/aider-composer#7]
When I use Homebrew Python path: /opt/homebrew/bin. The extension cannot detect python executable. I think this is because the Python installed by Homebrew is named "python3" and doesn't have a "python" alias.

**Comment by callbacked** [comment]
I got python and pyenv through homebrew. Try running ``which python3``, and use that directory instead of the homebrew one.

when I ran it, it turned out to be ```/Users/alex/.pyenv/shims/python``` and not ```/opt/homebrew/bin/python3```

Perhaps it's something similar in your case, where the intended executable is elsewhere.

**Comment by lee88688** [comment]
@callbacked may be the right. I detect the command named `python`, so `python3` is not work. because I don't have Mac, some errors will not be detected.

**Comment by jialanxin** [comment]
Finally, I create a virtual environment that contains python, aider-chat and flake. All in one /bin directory. 😊
